# Usa la imagen base de PHP con Apache
FROM php:8.2-apache

# Establece el directorio de trabajo
WORKDIR /var/www/html

# Actualiza los paquetes e instala dependencias necesarias
RUN apt-get update && \
    apt-get install -y git zlib1g-dev libzip-dev && \
    rm -rf /var/lib/apt/lists/*

# Instala extensiones PHP necesarias
RUN docker-php-ext-install zip pdo pdo_mysql
    
# Clona el repositorio
RUN git clone https://maxi6np:'personal access token'@github.com/daw2-23-24-pdaw/cityExplorer-backend.git

# Copia el archivo de entorno
COPY ./CityExplorer_Backend/.env /var/www/html/cityExplorer-backend

# Instala Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Cambia el directorio de trabajo al repositorio clonado
WORKDIR /var/www/html/cityExplorer-backend

# Actualiza e instala dependencias del proyecto con Composer
RUN composer update && composer install

# Comando para iniciar Apache en primer plano
CMD ["apache2-foreground"]

# Cambia la propiedad y permisos de los directorios necesarios
RUN chown -R www-data:www-data storage bootstrap/cache && \
    chmod -R 775 storage && \
    chmod -R 775 bootstrap/cache && \
    chmod -R 777 public

# Desactiva el sitio por defecto de Apache
RUN a2dissite 000-default.conf

# Copia la configuración personalizada de Apache y la habilita
COPY web_laravel.conf /etc/apache2/sites-available
RUN a2ensite web_laravel.conf && a2enmod rewrite

# Expone el puerto 8000 para HTTP
EXPOSE 80
