FROM node:20.11.1

WORKDIR /app

# Instala git y nginx en una sola capa
RUN apt-get update && \
    apt-get install -y git nginx && \
    rm -rf /var/lib/apt/lists/*

# Clona el repositorio
RUN git clone https://maxi6np:'personal access token'@github.com/daw2-23-24-pdaw/cityExplorer-frontend.git

WORKDIR /app/cityExplorer-frontend

# Instala dependencias y construye el proyecto
RUN npm install && \
    npm install @rollup/rollup-linux-x64-gnu && \
    npm run build

# Configura nginx
COPY nginx.conf /etc/nginx/sites-available/nginx.conf
RUN ln -s /etc/nginx/sites-available/nginx.conf /etc/nginx/sites-enabled

# Copia archivos construidos al directorio web de nginx
RUN cp -r /app/cityExplorer-frontend/dist/* /var/www/html/

# Exponer el puerto 80
EXPOSE 80

# Comando para iniciar nginx
CMD ["nginx", "-g", "daemon off;"]
